### ISSUE TITLE
problems in this segmentation pipeline

### ISSUE THREAD

**Issue by yongmanlove** [ecker-lab/TreeLearn#8]
i am  so sorry to bother you
i meet some probles like this,i think  this file named L1W.laz wrong, do you think?  
then how can i slove it.  

Traceback (most recent call last):
  File "/home/keeping/下载/TreeLearn/tools/pipeline/pipeline.py", line 183, in <module>
    run_treelearn_pipeline(config, args.config)
  File "/home/keeping/下载/TreeLearn/tools/pipeline/pipeline.py", line 47, in run_treelearn_pipeline
    generate_tiles(config.sample_generation, config.forest_path, logger, config.save_cfg.return_type)
  File "/home/keeping/下载/TreeLearn/tree_learn/util/pipeline.py", line 43, in generate_tiles
    data = load_data(forest_path)
  File "/home/keeping/下载/TreeLearn/tree_learn/util/data_preparation.py", line 27, in load_data
    las_file = laspy.read(path)
  File "/home/keeping/anaconda3/envs/TreeLearn/lib/python3.9/site-packages/laspy/lib.py", line 254, in read_las
    return reader.read()
  File "/home/keeping/anaconda3/envs/TreeLearn/lib/python3.9/site-packages/laspy/lasreader.py", line 126, in read
    points = self.read_points(-1)
  File "/home/keeping/anaconda3/envs/TreeLearn/lib/python3.9/site-packages/laspy/lasreader.py", line 107, in read_points
    self.point_source.read_n_points(n), self.header.point_format
  File "/home/keeping/anaconda3/envs/TreeLearn/lib/python3.9/site-packages/laspy/lasreader.py", line 75, in point_source
    self._point_source = self._create_point_source(self._source)
  File "/home/keeping/anaconda3/envs/TreeLearn/lib/python3.9/site-packages/laspy/lasreader.py", line 291, in _create_point_source
    point_source = self._create_laz_backend(source)
  File "/home/keeping/anaconda3/envs/TreeLearn/lib/python3.9/site-packages/laspy/lasreader.py", line 286, in _create_laz_backend
    raise last_error
  File "/home/keeping/anaconda3/envs/TreeLearn/lib/python3.9/site-packages/laspy/lasreader.py", line 274, in _create_laz_backend
    reader: IPointReader = backend.create_reader(
  File "/home/keeping/anaconda3/envs/TreeLearn/lib/python3.9/site-packages/laspy/_compression/backend.py", line 61, in create_reader
    return self._get().create_reader(
  File "/home/keeping/anaconda3/envs/TreeLearn/lib/python3.9/site-packages/laspy/_compression/lazrsbackend.py", line 50, in create_reader
    return LazrsPointReader(
  File "/home/keeping/anaconda3/envs/TreeLearn/lib/python3.9/site-packages/laspy/_compression/lazrsbackend.py", line 85, in __init__
    self.decompressor = lazrs.LasZipDecompressor(
lazrs.LazrsError: IoError: failed to fill whole buffer

**Comment by yongmanlove** [comment]
ok  this problem is solved.    but  cuda version how to fit?  
 RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
